M651, PCB REV A&B, NEGATIVE OUTPUT CONVERTER (3 3-input NAND)

Note:  must probe all outputs.

       AB2, disconnect tester, connect to -15V

       AD2, disconnect tester, output 1
       AE2, disconnect tester, connect to ground or open (slew control 1)

       AK2, disconnect tester, output 2
       AL2, disconnect tester, connect to ground or open (slew control 2)

       AR2, disconnect tester, connect to ground or open (slew control 3)
       AS2, disconnect tester, output 3


PINS
 1 I AF2 E1-1     input 1A,  NAND 1A,1B,1C is output 1 E1-12
 2 I AH2 E1-2     input 1B,  NAND 1A,1B,1C is output 1 E1-12
 3 I AJ2 E1-13    input 1C,  NAND 1A,1B,1C is output 1 E1-12
 4 I AP2 E1-9     input 2A,  NAND 2A,2B,2C is output 2 E1-8
 5 I AN2 E1-10    input 2B,  NAND 2A,2B,2C is output 2 E1-8
 6 I AM2 E1-11    input 2C,  NAND 2A,2B,2C is output 2 E1-8
 7 I AT2 E1-3     input 3A,  NAND 3A,3B,3C is output 3 E1-6
 8 I AU2 E1-4     input 3B,  NAND 3A,3B,3C is output 3 E1-6
 9 I AV2 E1-5     input 3C,  NAND 3A,3B,3C is output 3 E1-6

IIIIIIIII
000000000
001
010
011
100
101
110
111
000000000
   001
   010
   011
   100
   101
   110
   111
000000000
      001
      010
      011
      100
      101
      110
      111
111111111
110
101
100
011
010
001
000
111111111
   110
   101
   100
   011
   010
   001
   000
111111111
      110
      101
      100
      011
      010
      001
      000
END

