M900 FRONT PANEL DRIVER for 2 connectors

PINS
 1 I AJ2        paddle E  PC0
 2 I AS1        paddle E  PC1
 3 I AP2        paddle E  PC2
 4 I AN1	paddle E  PC3
 5 I AC1	paddle E  PC4
 6 I AD1        paddle e 
 7 I AU2
 8 I AR2
 9 I AK2
10 I AE2
11 I AL1
12 I AE1
13 I AR1
14 I AP1   
15 I AF2
16 I AD2
17 I AK1
18 I AA1
19 I AV2
20 I AT2
21 I AJ1
22 I AH2
23 I AM1
24 I AB1
25 I AS2
26 I AM2
27 I AN2
28 I AL2
29 I AF1
30 I AH1
31 I BJ2
32 I BS1
33 I BP2
34 I BN1
35 I BC1
36 I BD1
37 I BU2
38 I BR2
39 I BK2
40 I BE2
41 I BL1
42 I BE1
43 I BR1
44 I BP1   
45 I BF2
46 I BD2
47 I BK1
48 I BA1
49 I BV2
50 I BT2
51 I BJ1
52 I BH2
53 I BM1
54 I BB1
55 I BS2
56 I BM2
57 I BN2
58 I BL2
59 I BF1
60 I BH1

IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
111111111111111111111111111111111111111111111111111111111111
0
1
 0
 1
  0
  1
   0
   1
    0
    1
     0
     1
      0
      1
       0
       1
        0
        1
         0
         1
          0
          1
           0
           1
            0
            1
             0
             1
              0
              1
               0
               1
                0
                1
                 0
                 1
                  0
                  1
                   0
                   1
                    0
                    1
                     0
                     1
                      0
                      1
                       0
                       1
                        0
                        1
                         0
                         1
                          0
                          1
                           0
                           1
                            0
                            1
                             0
                             1
                              0
                              1
                               0
                               1
                                0
                                1
                                 0
                                 1
                                  0
                                  1
                                   0
                                   1
                                    0
                                    1
                                     0
                                     1
                                      0
                                      1
                                       0
                                       1
                                        0
                                        1
                                         0
                                         1
                                          0
                                          1
                                           0
                                           1
                                            0
                                            1
                                             0
                                             1
                                              0
                                              1
                                               0
                                               1
                                                0
                                                1
                                                 0
                                                 1
                                                  0
                                                  1
                                                   0
                                                   1
                                                    0
                                                    1
                                                     0
                                                     1
                                                      0
                                                      1
                                                       0
                                                       1
                                                        0
                                                        1
                                                         0
                                                         1
                                                          0
                                                          1
                                                           0
111111111111111111111111111111111111111111111111111111111111
101010101010101010101010101010101010101010101010101010101010
010101010101010101010101010101010101010101010101010101010101
000000000000000000000000000000000000000000000000000000000000
111111111111111111111111111111111111111111111111111111111111
END
