M900 FRONT PANEL DRIVER

PINS
 1 I AJ2
 2 I AS1
 3 I AP2
 4 I AN1
 5 I AC1
 6 I AD1
 7 I AU2
 8 I AR2
 9 I AK2
10 I AE2
11 I AL1
12 I AE1
13 I AR1
14 I AP1   
15 I AF2
16 I AD2
17 I AK1
18 I AA1
19 I AV2
20 I AT2
21 I AJ1
22 I AH2
23 I AM1
24 I AB1
25 I AS2
26 I AM2
27 I AN2
28 I AL2
29 I AF1
30 I AH1

IIIIIIIIIIIIIIIIIIIIIIIIIIIIII
111111111111111111111111111111
0
1
 0
 1
  0
  1
   0
   1
    0
    1
     0
     1
      0
      1
       0
       1
        0
        1
         0
         1
          0
          1
           0
           1
            0
            1
             0
             1
              0
              1
               0
               1
                0
                1
                 0
                 1
                  0
                  1
                   0
                   1
                    0
                    1
                     0
                     1
                      0
                      1
                       0
                       1
                        0
                        1
                         0
                         1
                          0
                          1
                           0
                           1
                            0
                            1
                             0
111111111111111111111111111111
END
